// Code generated by "stringer -type=SyncMessageType"; DO NOT EDIT.

package syncmessagetype

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ADD_OBJECT-1]
	_ = x[MOVE_OBJECT-2]
	_ = x[REMOVE_OBJECT-3]
	_ = x[CHANGE_OBJECT-4]
	_ = x[VILLAGE_HANDOFF_QUERY-5]
	_ = x[SERVER_CHANGE_OBJECT-6]
	_ = x[MOVE_PLAYER-7]
	_ = x[REMOVE_PLAYER-8]
	_ = x[CHAT-9]
	_ = x[START_EVENT-10]
	_ = x[STOP_EVENT-11]
	_ = x[EMOTE-12]
	_ = x[BIND_USER_NOTIFY-13]
	_ = x[PAUSE_NPC-14]
	_ = x[RESUME_NPC-15]
	_ = x[UPDATE_NPC_SCRIPT-16]
	_ = x[NOTIFICATION-17]
	_ = x[CLIENT_TEST-18]
	_ = x[ADD_ITEM-19]
	_ = x[EVICT-20]
	_ = x[ENTER_LOC-21]
	_ = x[EXIT_LOC-22]
	_ = x[ECHO-23]
	_ = x[GET_VILLAGE-24]
	_ = x[REFRESH-25]
	_ = x[BIND-26]
	_ = x[BIND_QUERY-27]
	_ = x[BIND_VILLAGE_NOTIFY-28]
	_ = x[VILLAGE_HANDOFF-29]
	_ = x[FIND_SERVER-30]
	_ = x[UPDATE_FILTER-31]
	_ = x[SEND_NOTIFY-32]
	_ = x[LOGIN-33]
	_ = x[UPDATE_USER_INFO-34]
	_ = x[UPDATE_USER_FRIENDS-35]
	_ = x[UPDATE_USER_GROUPS-36]
	_ = x[MANAGE_USER_FRIENDS-37]
	_ = x[MANAGE_USER_GROUPS-38]
	_ = x[LIST_SERVERS-39]
	_ = x[LIST_VILLAGES-40]
	_ = x[LIST_USERS-41]
	_ = x[MOVE_VILLAGE-42]
	_ = x[START_NPCS-43]
	_ = x[STOP_NPCS-44]
	_ = x[USER_SESSION_HANDOFF-45]
	_ = x[EMOTE_SVC-46]
	_ = x[ACTION-47]
	_ = x[LOGOUT-48]
	_ = x[CLOSE_ZONE-49]
	_ = x[TERMINATE_USER_SESSION-50]
	_ = x[GET_PLAYER_COUNT-51]
	_ = x[UPDATE_LOCATION-52]
	_ = x[HEARTBEAT_NOTIFY-54]
	_ = x[RELOGIN-55]
}

const (
	_SyncMessageType_name_0 = "ADD_OBJECTMOVE_OBJECTREMOVE_OBJECTCHANGE_OBJECTVILLAGE_HANDOFF_QUERYSERVER_CHANGE_OBJECTMOVE_PLAYERREMOVE_PLAYERCHATSTART_EVENTSTOP_EVENTEMOTEBIND_USER_NOTIFYPAUSE_NPCRESUME_NPCUPDATE_NPC_SCRIPTNOTIFICATIONCLIENT_TESTADD_ITEMEVICTENTER_LOCEXIT_LOCECHOGET_VILLAGEREFRESHBINDBIND_QUERYBIND_VILLAGE_NOTIFYVILLAGE_HANDOFFFIND_SERVERUPDATE_FILTERSEND_NOTIFYLOGINUPDATE_USER_INFOUPDATE_USER_FRIENDSUPDATE_USER_GROUPSMANAGE_USER_FRIENDSMANAGE_USER_GROUPSLIST_SERVERSLIST_VILLAGESLIST_USERSMOVE_VILLAGESTART_NPCSSTOP_NPCSUSER_SESSION_HANDOFFEMOTE_SVCACTIONLOGOUTCLOSE_ZONETERMINATE_USER_SESSIONGET_PLAYER_COUNTUPDATE_LOCATION"
	_SyncMessageType_name_1 = "HEARTBEAT_NOTIFYRELOGIN"
)

var (
	_SyncMessageType_index_0 = [...]uint16{0, 10, 21, 34, 47, 68, 88, 99, 112, 116, 127, 137, 142, 158, 167, 177, 194, 206, 217, 225, 230, 239, 247, 251, 262, 269, 273, 283, 302, 317, 328, 341, 352, 357, 373, 392, 410, 429, 447, 459, 472, 482, 494, 504, 513, 533, 542, 548, 554, 564, 586, 602, 617}
	_SyncMessageType_index_1 = [...]uint8{0, 16, 23}
)

func (i SyncMessageType) String() string {
	switch {
	case 1 <= i && i <= 52:
		i -= 1
		return _SyncMessageType_name_0[_SyncMessageType_index_0[i]:_SyncMessageType_index_0[i+1]]
	case 54 <= i && i <= 55:
		i -= 54
		return _SyncMessageType_name_1[_SyncMessageType_index_1[i]:_SyncMessageType_index_1[i+1]]
	default:
		return "SyncMessageType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
