// Code generated by "stringer -type=ServiceClass"; DO NOT EDIT.

package serviceclass

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[USER_SERVER-18]
	_ = x[SYNC_SERVER-19]
	_ = x[LOCATION-20]
	_ = x[CLIENT - -1]
}

const (
	_ServiceClass_name_0 = "CLIENT"
	_ServiceClass_name_1 = "USER_SERVERSYNC_SERVERLOCATION"
)

var (
	_ServiceClass_index_1 = [...]uint8{0, 11, 22, 30}
)

func (i ServiceClass) String() string {
	switch {
	case i == -1:
		return _ServiceClass_name_0
	case 18 <= i && i <= 20:
		i -= 18
		return _ServiceClass_name_1[_ServiceClass_index_1[i]:_ServiceClass_index_1[i+1]]
	default:
		return "ServiceClass(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
