package notify

import (
	"github.com/dv1x3r/amazing-core/internal/network/gsf"
	"github.com/dv1x3r/amazing-core/internal/network/gsf/types"
)

// Move is the payload for GSFMoveNotify.
type Move struct {
	Pos       []types.Position
	QTH       types.QTH
	SecondQTH types.QTH

	// Seq is the movement sequence byte generated by the client.
	Seq byte

	// UID is the moving player OID from the client uid field.
	UID types.OID

	// VID is the village/context OID from the client vid field.
	VID types.OID
}

func (n *Move) Deserialize(reader gsf.ProtocolReader) {
	n.Pos = gsf.ReadSlice(reader, func() types.Position {
		var value types.Position
		reader.ReadObject(&value)
		return value
	})
	reader.ReadObject(&n.QTH)
	reader.ReadObject(&n.SecondQTH)
	n.Seq = reader.GetByte()
	reader.ReadObject(&n.UID)
	reader.ReadObject(&n.VID)
}
