// Code generated by "stringer -type=ClientMessageType"; DO NOT EDIT.

package clientmessagetype

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ADD_OBJECT-1]
	_ = x[MOVE_OBJECT-2]
	_ = x[REMOVE_OBJECT-3]
	_ = x[CHANGE_OBJECT-4]
	_ = x[SERVER_CHANGE_OBJECT-5]
	_ = x[MOVE_PLAYER-6]
	_ = x[REMOVE_PLAYER-7]
	_ = x[CHAT-8]
	_ = x[START_EVENT-9]
	_ = x[STOP_EVENT-10]
	_ = x[EMOTE-11]
	_ = x[CHANGE_WEIGHT-12]
	_ = x[PAUSE-13]
	_ = x[RESUME-14]
	_ = x[NOTIFICATION-16]
	_ = x[CHANGE_SERVER-17]
	_ = x[SEND_NOTIFY-18]
	_ = x[INT_LIST-19]
	_ = x[ADD_PLAYER-20]
	_ = x[UPDATE_NPCS-21]
	_ = x[STOP_NPC-22]
	_ = x[MINIMAP-23]
	_ = x[POS_RECAP-24]
	_ = x[ACTION-25]
	_ = x[EVICT-26]
	_ = x[ONLINE_STATUS-27]
	_ = x[CHANGE_OBJECT_STATE-28]
}

const (
	_ClientMessageType_name_0 = "ADD_OBJECTMOVE_OBJECTREMOVE_OBJECTCHANGE_OBJECTSERVER_CHANGE_OBJECTMOVE_PLAYERREMOVE_PLAYERCHATSTART_EVENTSTOP_EVENTEMOTECHANGE_WEIGHTPAUSERESUME"
	_ClientMessageType_name_1 = "NOTIFICATIONCHANGE_SERVERSEND_NOTIFYINT_LISTADD_PLAYERUPDATE_NPCSSTOP_NPCMINIMAPPOS_RECAPACTIONEVICTONLINE_STATUSCHANGE_OBJECT_STATE"
)

var (
	_ClientMessageType_index_0 = [...]uint8{0, 10, 21, 34, 47, 67, 78, 91, 95, 106, 116, 121, 134, 139, 145}
	_ClientMessageType_index_1 = [...]uint8{0, 12, 25, 36, 44, 54, 65, 73, 80, 89, 95, 100, 113, 132}
)

func (i ClientMessageType) String() string {
	switch {
	case 1 <= i && i <= 14:
		i -= 1
		return _ClientMessageType_name_0[_ClientMessageType_index_0[i]:_ClientMessageType_index_0[i+1]]
	case 16 <= i && i <= 28:
		i -= 16
		return _ClientMessageType_name_1[_ClientMessageType_index_1[i]:_ClientMessageType_index_1[i+1]]
	default:
		return "ClientMessageType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
