// Code generated by "stringer -type=OnlineStatusValue"; DO NOT EDIT.

package onlinestatusvalue

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OFFLINE-0]
	_ = x[APPEAR_OFFLINE-1]
	_ = x[ONLINE-2]
	_ = x[BUSY-3]
}

const _OnlineStatusValue_name = "OFFLINEAPPEAR_OFFLINEONLINEBUSY"

var _OnlineStatusValue_index = [...]uint8{0, 7, 21, 27, 31}

func (i OnlineStatusValue) String() string {
	if i < 0 || i >= OnlineStatusValue(len(_OnlineStatusValue_index)-1) {
		return "OnlineStatusValue(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OnlineStatusValue_name[_OnlineStatusValue_index[i]:_OnlineStatusValue_index[i+1]]
}
