// Code generated by "stringer -type=ChatChannelTypeValue"; DO NOT EDIT.

package chatchanneltypevalue

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PRIVATE-0]
	_ = x[PRIVATE_GROUP-1]
	_ = x[LOCAL-2]
}

const _ChatChannelTypeValue_name = "PRIVATEPRIVATE_GROUPLOCAL"

var _ChatChannelTypeValue_index = [...]uint8{0, 7, 20, 25}

func (i ChatChannelTypeValue) String() string {
	if i < 0 || i >= ChatChannelTypeValue(len(_ChatChannelTypeValue_index)-1) {
		return "ChatChannelTypeValue(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ChatChannelTypeValue_name[_ChatChannelTypeValue_index[i]:_ChatChannelTypeValue_index[i+1]]
}
