[book]
title = "Amazing Core mdBook"
authors = ["dv1x3r"]
description = "Docs for open source Amazing World game server written in Go"
language = "en"

[output.html]
no-section-label = true
git-repository-url = "https://github.com/dv1x3r/amazing-core"
edit-url-template = "https://github.com/dv1x3r/amazing-core/edit/master/docs/{path}"

[output.html.fold]
enable = true
level = 1

[output.html.search.chapter]
"tools/cache-archive.md" = { enable = false }
"tools/gsfoid-calculator.md" = { enable = false }
