// Code generated by "stringer -type=SessionStatus"; DO NOT EDIT.

package sessionstatus

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[IN_PROGRESS-0]
	_ = x[LOGGED_OUT-1]
	_ = x[TIMED_OUT-2]
	_ = x[FORCED_LOGOUT-3]
	_ = x[LOGOUT_IN_PROGRESS-4]
	_ = x[INCORRECT_PASSWORD-5]
	_ = x[INVALID_LOGIN-6]
	_ = x[SYSTEM_ERROR-7]
	_ = x[USER_NOT_ACTIVE-8]
	_ = x[USER_UNAPPROVED-9]
	_ = x[ACCOUNT_EXPIRED-10]
	_ = x[USER_EXISTS-11]
}

const _SessionStatus_name = "IN_PROGRESSLOGGED_OUTTIMED_OUTFORCED_LOGOUTLOGOUT_IN_PROGRESSINCORRECT_PASSWORDINVALID_LOGINSYSTEM_ERRORUSER_NOT_ACTIVEUSER_UNAPPROVEDACCOUNT_EXPIREDUSER_EXISTS"

var _SessionStatus_index = [...]uint8{0, 11, 21, 30, 43, 61, 79, 92, 104, 119, 134, 149, 160}

func (i SessionStatus) String() string {
	if i < 0 || i >= SessionStatus(len(_SessionStatus_index)-1) {
		return "SessionStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SessionStatus_name[_SessionStatus_index[i]:_SessionStatus_index[i+1]]
}
